name: Stock Data Model Build / Test / Deploy
run-name: ${{ github.repository }} - ${{ github.ref }} - ${{ github.run_number }}
on:
  push:
    branches:
      - **
  pull_request:
    branches:
      - dev
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Build Package
        run: |
          pip install poetry
          poetry build
      - name: Upload Package
        run: |
          poetry config repositories.pypifeed ${{ secrets.AZURE_PYPI_REPO }}
          poetry publish -r pypifeed -u a -p ${{ secrets.AZURE_PYPI_PASSWORD }}
  
  # ${{ if github.ref == 'refs/heads/main' or github.ref == 'refs/heads/dev' or github.ref == 'refs/heads/uat' }}:
  #   deploy: