"""Core4

Revision ID: 1c81dcbae553
Revises: bc6aa2a11adc
Create Date: 2023-03-13 20:21:00.564700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c81dcbae553'
down_revision = 'bc6aa2a11adc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickers_currency_id', table_name='tickers')
    op.drop_constraint('tickers_currency_id_fkey', 'tickers', type_='foreignkey')
    op.drop_column('tickers', 'currency_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickers', sa.Column('currency_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tickers_currency_id_fkey', 'tickers', 'currencies', ['currency_id'], ['id'])
    op.create_index('ix_tickers_currency_id', 'tickers', ['currency_id'], unique=False)
    # ### end Alembic commands ###
