"""Core2

Revision ID: 371ace378bc5
Revises: fc608628c9db
Create Date: 2023-03-13 12:10:18.990292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371ace378bc5'
down_revision = 'fc608628c9db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'eod_ingestor_job_data_locations', 'eod_ingestor_data_stores', ['data_store_id'], ['id'])
    op.create_foreign_key(None, 'eod_ingestor_job_status', 'eod_ingestor_data_stores', ['data_store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eod_ingestor_job_status', type_='foreignkey')
    op.drop_constraint(None, 'eod_ingestor_job_data_locations', type_='foreignkey')
    # ### end Alembic commands ###
