"""Core6

Revision ID: 72c8bc8d8bc1
Revises: d8ae2613706b
Create Date: 2023-03-13 21:38:17.871876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72c8bc8d8bc1'
down_revision = 'd8ae2613706b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
