"""init

Revision ID: 7b4dd2fa79cd
Revises: 
Create Date: 2023-03-26 03:26:52.074557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4dd2fa79cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=False)
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    op.create_index(op.f('ix_countries_name'), 'countries', ['name'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=False)
    op.create_index(op.f('ix_currencies_id'), 'currencies', ['id'], unique=False)
    op.create_index(op.f('ix_currencies_name'), 'currencies', ['name'], unique=False)
    op.create_table('eod_ingestor_data_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.String(), nullable=True),
    sa.Column('container', sa.String(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_ingestor_data_stores_container'), 'eod_ingestor_data_stores', ['container'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_data_stores_id'), 'eod_ingestor_data_stores', ['id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_data_stores_name'), 'eod_ingestor_data_stores', ['name'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_data_stores_subscription_id'), 'eod_ingestor_data_stores', ['subscription_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_data_stores_tenant_id'), 'eod_ingestor_data_stores', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_data_stores_url'), 'eod_ingestor_data_stores', ['url'], unique=False)
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('abbr', sa.String(), nullable=True),
    sa.Column('dst', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timezones_abbr'), 'timezones', ['abbr'], unique=False)
    op.create_index(op.f('ix_timezones_dst'), 'timezones', ['dst'], unique=False)
    op.create_index(op.f('ix_timezones_id'), 'timezones', ['id'], unique=False)
    op.create_index(op.f('ix_timezones_name'), 'timezones', ['name'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_country_id'), 'cities', ['country_id'], unique=False)
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('acronym', sa.String(), nullable=True),
    sa.Column('mic', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('timezone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exchanges_acronym'), 'exchanges', ['acronym'], unique=False)
    op.create_index(op.f('ix_exchanges_city_id'), 'exchanges', ['city_id'], unique=False)
    op.create_index(op.f('ix_exchanges_country_id'), 'exchanges', ['country_id'], unique=False)
    op.create_index(op.f('ix_exchanges_id'), 'exchanges', ['id'], unique=False)
    op.create_index(op.f('ix_exchanges_mic'), 'exchanges', ['mic'], unique=False)
    op.create_index(op.f('ix_exchanges_name'), 'exchanges', ['name'], unique=True)
    op.create_index(op.f('ix_exchanges_timezone_id'), 'exchanges', ['timezone_id'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('exchange_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_exchange_id'), 'tickers', ['exchange_id'], unique=False)
    op.create_index(op.f('ix_tickers_id'), 'tickers', ['id'], unique=False)
    op.create_index(op.f('ix_tickers_name'), 'tickers', ['name'], unique=False)
    op.create_index(op.f('ix_tickers_ticker'), 'tickers', ['ticker'], unique=False)
    op.create_table('eod_ingestor_job_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('data_store_id', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('timezone_id', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['data_store_id'], ['eod_ingestor_data_stores.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ),
    sa.ForeignKeyConstraint(['timezone_id'], ['timezones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_ingestor_job_status_data_store_id'), 'eod_ingestor_job_status', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_end_date'), 'eod_ingestor_job_status', ['end_date'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_id'), 'eod_ingestor_job_status', ['id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_name'), 'eod_ingestor_job_status', ['name'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_start_date'), 'eod_ingestor_job_status', ['start_date'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_ticker_id'), 'eod_ingestor_job_status', ['ticker_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_status_timezone_id'), 'eod_ingestor_job_status', ['timezone_id'], unique=False)
    op.create_table('eod_ingestor_job_data_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time_generated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('job_status_id', sa.Integer(), nullable=True),
    sa.Column('data_store_id', sa.Integer(), nullable=True),
    sa.Column('blob', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['data_store_id'], ['eod_ingestor_data_stores.id'], ),
    sa.ForeignKeyConstraint(['job_status_id'], ['eod_ingestor_job_status.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eod_ingestor_job_data_locations_blob'), 'eod_ingestor_job_data_locations', ['blob'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_data_locations_data_store_id'), 'eod_ingestor_job_data_locations', ['data_store_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_data_locations_id'), 'eod_ingestor_job_data_locations', ['id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_data_locations_job_status_id'), 'eod_ingestor_job_data_locations', ['job_status_id'], unique=False)
    op.create_index(op.f('ix_eod_ingestor_job_data_locations_name'), 'eod_ingestor_job_data_locations', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_eod_ingestor_job_data_locations_name'), table_name='eod_ingestor_job_data_locations')
    op.drop_index(op.f('ix_eod_ingestor_job_data_locations_job_status_id'), table_name='eod_ingestor_job_data_locations')
    op.drop_index(op.f('ix_eod_ingestor_job_data_locations_id'), table_name='eod_ingestor_job_data_locations')
    op.drop_index(op.f('ix_eod_ingestor_job_data_locations_data_store_id'), table_name='eod_ingestor_job_data_locations')
    op.drop_index(op.f('ix_eod_ingestor_job_data_locations_blob'), table_name='eod_ingestor_job_data_locations')
    op.drop_table('eod_ingestor_job_data_locations')
    op.drop_index(op.f('ix_eod_ingestor_job_status_timezone_id'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_ticker_id'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_start_date'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_name'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_id'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_end_date'), table_name='eod_ingestor_job_status')
    op.drop_index(op.f('ix_eod_ingestor_job_status_data_store_id'), table_name='eod_ingestor_job_status')
    op.drop_table('eod_ingestor_job_status')
    op.drop_index(op.f('ix_tickers_ticker'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_name'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_id'), table_name='tickers')
    op.drop_index(op.f('ix_tickers_exchange_id'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_exchanges_timezone_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_name'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_mic'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_country_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_city_id'), table_name='exchanges')
    op.drop_index(op.f('ix_exchanges_acronym'), table_name='exchanges')
    op.drop_table('exchanges')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_country_id'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_timezones_name'), table_name='timezones')
    op.drop_index(op.f('ix_timezones_id'), table_name='timezones')
    op.drop_index(op.f('ix_timezones_dst'), table_name='timezones')
    op.drop_index(op.f('ix_timezones_abbr'), table_name='timezones')
    op.drop_table('timezones')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_url'), table_name='eod_ingestor_data_stores')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_tenant_id'), table_name='eod_ingestor_data_stores')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_subscription_id'), table_name='eod_ingestor_data_stores')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_name'), table_name='eod_ingestor_data_stores')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_id'), table_name='eod_ingestor_data_stores')
    op.drop_index(op.f('ix_eod_ingestor_data_stores_container'), table_name='eod_ingestor_data_stores')
    op.drop_table('eod_ingestor_data_stores')
    op.drop_index(op.f('ix_currencies_name'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_id'), table_name='currencies')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    op.drop_index(op.f('ix_countries_name'), table_name='countries')
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
