"""Core4

Revision ID: bc6aa2a11adc
Revises: eff716a6930c
Create Date: 2023-03-13 20:01:28.660650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc6aa2a11adc'
down_revision = 'eff716a6930c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchanges_acronym', table_name='exchanges')
    op.create_index(op.f('ix_exchanges_acronym'), 'exchanges', ['acronym'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchanges_acronym'), table_name='exchanges')
    op.create_index('ix_exchanges_acronym', 'exchanges', ['acronym'], unique=False)
    # ### end Alembic commands ###
