"""Core5

Revision ID: d8ae2613706b
Revises: 1c81dcbae553
Create Date: 2023-03-13 21:06:58.216357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ae2613706b'
down_revision = '1c81dcbae553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exchanges_mic', table_name='exchanges')
    op.create_index(op.f('ix_exchanges_mic'), 'exchanges', ['mic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exchanges_mic'), table_name='exchanges')
    op.create_index('ix_exchanges_mic', 'exchanges', ['mic'], unique=False)
    # ### end Alembic commands ###
